### ISSUE TITLE
There is a way to disable oauth_proxy?

### ISSUE THREAD

**Issue by mcianc** [MrSwitch/hello.js#133]
Hello I'm developing a module for box.com
https://developers.box.com/docs/#oauth-2

seem oauth_proxy interfear with auth procedure.

There is a parameter to disable proxy?

**Comment by azam** [comment]
@MrSwitch 

I am using hello.js v1.5.0 .

I am trying out Box.com's OAuth2 with hello.js, but as with @mcianc , I do not want to use oauth_proxy. I have oauth_proxy set to an empty string at the init params. 

Since hello.all.js does not contain the box.js module by default, first I have to put it in manually as is from https://github.com/MrSwitch/hello.js/blob/master/src/modules/box.js . The OAuth login dance to Box.com is fine, but right after the redirect page is loaded (hello is included on the page), it tries to redirect again to "undefined", carrying with it the parameters from the initial redirect.

I can see responseHandler is responsible for the redirect, but why should it re-redirect the page when it has the oauth code to exchange for access token already?

Can you provide some sample code for Box.com which does not involve a proxy?

**Comment by MrSwitch** [comment]
@azam if your still stuck please create a new issue. thnks
