### ISSUE TITLE
Use postMessage to close popup instead of .close

### ISSUE THREAD

**Issue by RangerMauve** [MrSwitch/hello.js#211]
I'm getting issues with CORS preventing Hello.JS from being able to close it's popups after the window is finished.

Since hello.js is being loaded into the window, it should be possible to have it listen for a postMessage call which will trigger it to close itself.

This would allow having the redirect hosted on a different domain/protocol than the current app.

Currently I'm having issues using this with apps served from the filesystem (embedded in mobile apps for instance) and it'd be nice if this was changed.

**Comment by MrSwitch** [comment]
Popup windows close themselves. There is a bug in ios that might be the problem.

**Comment by RangerMauve** [comment]
Really? I might be doing something wrong then. My code looks something like the following:

https://mysite.com/redirect.html
``` html
<!DOCTYPE html>
<title>Redirecting</title>
<script src="hello.js"></script>
```

index.js of my app
``` javascript
hello.init({
 google: "mykey"
}, {
 redirect_uri: "https://mysite.com/redirect.html"
});
hello("google").login(on_login);
```

In my Google console I've configured it to allow the redirect URI properly.
The app is on a different domain than the redirect.
The popup appears, I go through google, then it redirects to the redirect page properly.
After redirecting, however, it keeps the window open. Opening the dev tools within the popup mentions that it can't access a frame with a different origin.
The app's page just sits there like nothing happened, until I close the popup. When the popup is closed, I get an error fetching the auth data.

**Comment by MrSwitch** [comment]
Are you building this in phonegap. Because it should work. 

If your building for the web browser then the redirect_uri needs to be on the same domain.

**Comment by RangerMauve** [comment]
Currently it's in browser, but it is going to be going into node-webkit and phonegap as well.

Is there no way to circumvent the same domain requirement?

**Comment by RangerMauve** [comment]
It looks like the issue is more related to the popup trying to access the parent window. This happens when the domain doesn't match in node-webkit or when I try to run it from the filesystem in node-webkit

```
Uncaught SecurityError: Blocked a frame with origin "https://mysite.com" from accessing a frame with origin "file://".  The frame requesting access has a protocol of "https", the frame being accessed has a protocol of "file". Protocols must match.
hello.js:1696 authCallbackhello.js:1616 hello.utils.extend.responseHandlerhello.js:1761 (anonymous function)
```

**Comment by RangerMauve** [comment]
Any specific reason you're using [a callback](https://github.com/MrSwitch/hello.js/blob/6eeebca21eaf7f7854aeb500fadf8043d1a592d8/src/hello.js#L1696) in the parent window rather than using [postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage)?

**Comment by MrSwitch** [comment]
The implicit OAuth grant flow relies on the origin policy to verify the app is who they say they are. I dont know how you would secure this using postMessage. Certainly the `redirect_uri` page would need restrictions on which domains it can communicate with. This might be a little too complicated for some.

I'm not experienced with `node-webkit` but i assume it runs under the filesystem like phonegap apps do. Phonegap monitors the address of any inappbrowser window for the access_token, so gets around the same origin policy this way.

I recommend developing using a local webserver and register your local domain with thirdparty webservices, rather than viewing your site through "file://"

I'll do all i can to support node-webkit when you get round to it.
