### ISSUE TITLE
Handling Twitter session

### ISSUE THREAD

**Issue by julegatti** [MrSwitch/hello.js#237]
Everything almost works with `hello.js`. It's really a miracle. I'm using the Twitter module with [auth-server][1]. 
I have the same callback URL in Twitter and redirect_uri. 

In my own tests, I have a few questions:

1. Say I've already successfully logged in using hello.js, then `hello('twitter').getAuthResponse();` would return session info. However, if I revoke token access through Twitter's Apps page, and I reload my page it keeps telling [I'm logged in][2]; however, when I send a new request it fails:

    [X] GET https://api.twitter.com/1.1/account/verify_credentials.json?callback=_hellojs_6biqltg7&oauth_consumer_key=OWiXrrlqrGJur4YqpOphTGEnE&oauth_nonce=1e0ee8fb52f707000&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1430677510&oauth_token=2334549752-q9t9dQQTsHOZ3xuOKlZfjsT21WJHYJNeDhb8WwD&oauth_version=1.0&oauth_signature=UQiL7%2BmC7iBWiOSB1%2BtqfWwXYRE%3D

    EDIT: I guess what it's happening. Session is saved on Local Storage, and when revoking the app from Twitter Apps page the local stored data/cookie doesn't get noticed about that. Is there any workaround for this?

2. I though tokens would expire every hour, but as I see in the auth response it expires in a year from now. `expires_in` value is 0. Is there any why to modify the expire time?

3. In the case of running server code, could I just use hello.js to do the OAuth stuff and pass the user access & secret token key to a more complete Twitter API wrapper to make all the API requests?

4. If hello.js uses only needs the client ID, which is visible in the source code, any other app could use hello.js using my client ID. Isn't it dangerous?

  [1]: https://auth-server.herokuapp.com
  [2]: http://i.imgur.com/ZumRHTw.png

**Comment by MrSwitch** [comment]
Hi @julegatti 

There's a lot of questions there but i'll try to explain

1. Yes there is an issue here, and there are other cases where we might need to reassign user credentials too. The best thing is to catch the error and provide a reauthenticate button to the user in that circumstance.

2. Tokens vary on how long they last, Twitter uses OAuth1 which unlike it's successor OAuth2 keeps tokens around for a lot longer.

3. This is pretty much what https://auth-server.herokuapp.com is doing

4. Your `client_id` is tied to the value of the `redirect url`. Another app could try using the same combination to trigger the authentication flow but because of the same-origin policy in the web browser their page would not be able to communicate with the popup on the other domain and be unable to read the token.

**Comment by julegatti** [comment]
thanks for replying!
1. ok
2. so, expire times depends on the protocol or is it a way to modify it?
3. mm yes
4. ok
