### ISSUE TITLE
library crashes when cookies are disabled

### ISSUE THREAD

**Issue by joeltello** [MrSwitch/hello.js#266]
if you disabled the cookies in the browser the library fails to initialize 

```TypeError: utils.url is not a function
    at Function.hello.utils.extend.init ```

I understand that it is not possible to preserve the state without cookies/localstorage but the library should not crash like that

**Comment by TomTasche** [comment]
i do not see the exact same error, but i think the reason is the same: cookies are disabled. for me, it throws a "SecurityError: DOM Exception 18". possibly more information here: http://apple.stackexchange.com/a/125588 and https://github.com/angular-translate/angular-translate/issues/629#issuecomment-48159812
