### ISSUE TITLE
[Security] Stop sending explicit requests to https://auth-server.herokuapp.com/proxy with code response type

### ISSUE THREAD

**Issue by diimpp** [MrSwitch/hello.js#283]
Hi,
To my surprise I just noticed that library sends requests to https://auth-server.herokuapp.com/proxy, when response type is changed to code.

How to reproduce:
```
hello('google').login({response_type: 'code'}).then(function(authResponse) {
...
}
```
On which one would get
```
 Could not find the credentials that match the provided client_id. Register your app credentials by visiting https//auth-server.herokuapp.com
```

I see it as security implication and would advise to remove default proxy setup and mention this server at docs instead.

Regards.

**Comment by MrSwitch** [comment]
**Firstly** i changed the title because your referring to the "Explicit" flow.

**Secondly:** can you explain how the default "oauth_proxy" might take advantage of an Authorization "code". Afterall if it does not know of the `client_secret` it can't access the API.

**Finally:**

*History*
I initially set it up as a shim for the services using OAuth1. And the library's intention was to make everything client-side and "implicit". So managing a auth1 shim server seemed like a win to achieve this and really only later came to support OAuth2 explicit flow since Github didn't allow the "implicit" pure client-side flow.

*Benefits*
As a default it has helped a great many people. By simply removing a step...

* ~~Set oauth_proxy in `hello.init(.., options)~~
* Register your keys at //auth-server

*Cons*
That said I totally get where your concerns come from. A colleague of mine, once thought i was introducing spyware into the project. :)

*Conclusion*
HelloJS acts like a service in many respects. Its a facade to lots of different thirdparty API's. The fact is that HelloJS needs a web service in order to make these other services play nicely. For instance, like NPM CLI tools need an online repository to pull in packages.

In both cases it would be a far clunkier setup if one had to go and first find out what that endpoint should be.

Thanks

**Comment by diimpp** [comment]
Thank you for detailed response. :)
