### ISSUE TITLE
Microsoft Edge window.open 'permission denied'

### ISSUE THREAD

**Issue by Hadrien-DELAITRE** [MrSwitch/hello.js#311]
Apparently the opening function 'popup' throws an error 'permission denied' on Microsoft Edge.

https://github.com/MrSwitch/hello.js/blob/master/src/hello.js#L1243

Do you have the same problem ?

**Comment by MrSwitch** [comment]
Haven't got Edge yet, downloading the VM tonight.

**Comment by MrSwitch** [comment]
I can't recreate this issues on MS Edge. Can you check the parameters which are being applied to `window.open`. Thanks

**Comment by MrSwitch** [comment]
inactive

**Comment by rickpern** [comment]
:+1: 

I believe this is still an issue. I just bought a new windows comp with Edge and i get the Permission denied error at the link that says `if (popup && popup.addEventListener)` https://github.com/MrSwitch/hello.js/blob/master/src/hello.js#L1266

I'm currently testing with Facebook login.  If you pass a function into the `callback` argument or into `then`, it is never executed because the event listener was never attached due to permission errors i presume.  

Workaround for now: don't rely on the callback or deferred and instead just listen for the `auth.login` to fire.

**Comment by SinisaG** [comment]
I confirm that this is an issue. 

Using latest hellojs version: 1.9.5

**Comment by MrSwitch** [comment]
Nope, https://adodson.com/hello.js/demos/profile.html works for me in Edge. Are you triggering the `hello.login` on a user click event?

**Comment by rickpern** [comment]
I've confirmed that the callback method works as specified in your demo, but the promise never resolves if you do `hello('facebook').login().then(function (e) { log("login", e) });`

**Comment by rickpern** [comment]
@MrSwitch you rock!  Thanks so much for the quick fix!!!

**Comment by Hadrien-DELAITRE** [comment]
:+1: thank you so much!

**Comment by SinisaG** [comment]
@MrSwitch thanks a lot for very quick fix!

**Comment by MrSwitch** [comment]
Reported issue to Microsoft please upvote https://connect.microsoft.com/IE/feedback/details/1948354/permission-denied-error-with-accessing-addeventlistener-of-a-popup
