### ISSUE TITLE
Refresh token

### ISSUE THREAD

**Issue by jmgamboa** [MrSwitch/hello.js#350]
Is there anyway to refresh access tokens via hello js credentials?

**Comment by MrSwitch** [comment]
Not sure i understand, "hello js credentials?"

```javascript
// When tokens expire, and the provider supports refreshing the tokens then this is called...
hello(network).login({display:'none'});
```

**Comment by jmgamboa** [comment]
by credentials i mean the authresponse object returned by hellojs with attributes like access token and client id.  Saving these to our DB will allows us to make additional calls to the google api with those "credentials." However these tokens expire within an hour. to ensure we are able to make those calls regardless of time we need the refresh token.

**Comment by MrSwitch** [comment]
There's a bit of missing documentation around the options here https://adodson.com/hello.js/#refresh-access-token explains a little about what HelloJS does itself. 

For OAuth1 services there's not much to do as tokens aren't "refreshed" , but rather constantly resigned on each request.

OAuth2 however will return a `refresh_token` in some instances which you can use in the backend when the client is offline. HelloJS is client-side focused so doesn't have much concern for that scenario, beyond processing "Authorization Code" (otherwise known as explicit login) with a `oauth_proxy` service to get a `refresh_token` and use the service again to refresh the `access_token` when the old one has expired.

To capture the `refresh_token` in your own app, you might like to just use the Explicit Login approach.

```javascript
hello.login({response_type:'code'}).then(...);
```
This can also be set in `hello.init(cred, options)` options.

The default `oauth_proxy` [//auth-server](https://auth-server.herokuapp.com) will return the `refresh_token` initially - you can then deliver it to your backend. Or you can make your own [node-oauth-shim](https://npmjs.com/package/oauth-shim) and intercept the `refresh_token` at its inception. An example of this is at https://github.com/MrSwitch/auth-server/blob/v0.1.0/app.js#L319
