### ISSUE TITLE
how do i get the twitter secret from the response

### ISSUE THREAD

**Issue by tawanda** [MrSwitch/hello.js#352]
hi guys, i want to use hello.js only to get the users access token and secret to send to my backend (my backend will be the one fetching all the tweets in a task), 

I placed a log like so 

```
twitter.login().then( function(r){ 
   console.log('response===>', r);
} 
```

and in the response i can se the access token, but there is no secret, is there a setting i can enable to get the secret

**Comment by MrSwitch** [comment]
If your backend is NodeJs you can use [oauth-shim](https://github.com/MrSwitch/node-oauth-shim) as your `oauth_proxy` to capture the authorization token response during login - without making an API request from the client.

Otherwise, you can deduce the OAuth1 consumer secret from the access_token which your looking at, as its formed by the service known as the `oauth_proxy` into a single string of the format:...

           consumer_key:consumer_secret@app_key

**Comment by tawanda** [comment]
Perfect!, thank you for the great library
