### ISSUE TITLE
auth-server.herokuapp.com is broken

### ISSUE THREAD

**Issue by adebisi-fa** [MrSwitch/hello.js#427]
Hello,

The proxy portal, hosted at https://auth-server.herokuapp.com/ appears to be broken.  It isn't functioning as at writing this.  

I couldn't register my apps with it, as a result.

Kindly help fix, asap.

Thanks for the great deal you're putting into hello.js. 

It's awesome!

**Comment by MrSwitch** [comment]
Whats the error message?

**Comment by adebisi-fa** [comment]
The site isn't loading at all. I think it's a javascript related error. Complaining of 'hello' being undefined.
![Screenshot of page.](https://cloud.githubusercontent.com/assets/1475313/15610850/557e0e5c-241f-11e6-9ddb-f982ce1d0137.png)

**Comment by MrSwitch** [comment]
Believe this is an SSL certificate issue in your browser.

https://adodson.com uses [Universal SSL](https://blog.cloudflare.com/introducing-universal-ssl/) from Cloudflare. I had problems on a corporate network because of some proxies didn't understand the SSL certificate - or something. Cloudflare support team directed me too...

- First check your on a decent browser https://support.cloudflare.com/hc/en-us/articles/204846347-Which-browsers-are-supported-for-Universal-SSL-
- Otherwise if you use Chrome, force an SSL type see https://zmap.io/sslv3/browsers.html#chrome-windows

Otherwise try another browser, sorry for this.
