### ISSUE TITLE
Client still thinks it's logged in, when provider authorization is revoked

### ISSUE THREAD

**Issue by chaodoze** [MrSwitch/hello.js#66]
Thanks for a really nice library!

One issue I found is that if I revoked an authorization say from Facebook, the library still thinks I'm logged in. Is there a way to fix that?

Also, if for whatever reason a user clears localStorage, all login info is also lost.

**Comment by chrisguerrero** [comment]
@MrSwitch I'm currently running into this same issue.

Because the auth token is stored in localStorage, calling `hello().login` succeeds even if access has been revoked by the provider.  At this point, calls to `hello().api()` will fail with error code 190 (sub code 466). How can I then prompt the user to re-grant access to my application? Would I call `hello().login` with the force option set to true?
